### ISSUE TITLE
Bug au lancement du serveur

### ISSUE THREAD

**Issue by marc-farre** [ForumDebats/dialoguea#2]
L'install s'est à priori bien passée, mais le serveur Node.Js ne veut pas se lancer :

```
$ node --version
v4.2.3
$ nodemon server
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server`
/var/www/dialoguea.co.tools/dialoguea/server/index.js:14
import log from './log'
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
[nodemon] app crashed - waiting for file changes before starting...
```

Peut-être une piste :
https://stackoverflow.com/questions/32346886/unexpected-reserved-word-import-in-node-js

Idem si je lance le serveur avec `node server start`

Et si j'essaye d'ajouter un utilisateur :

```
$ node server/adduser
/var/www/dialoguea/server/adduser.js:96
let start = function () {
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

Merci d'avance pour votre aide et ce beau projet qu'on essaye d'installer sur Communecter !

**Comment by flintforge** [comment]
Doc mise à jour,
Dialoguea côté serveur est en Ecma5.
`npm run dev` pour démarrer le serveur.

**Comment by marc-farre** [comment]
Merci beaucoup !
J'ai refait une install complète car j'ai vue que ça a bougé aussi dans le code et sur la version nvm

A l'install, tout se passe bien, à part ce message :
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
C'est parce que le serveur est sous Ubuntu 16.04, mais j'ai réglé le problème avec la commande `npm install --no-optional`

Par contre, si je fais `node server/adduser`, j'ai un autre message d'erreur (différent de mon 1er post) :
```
/var/www/dialoguea.co.tools/dialoguea/settings.js:8
export var configuration = {
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/dialoguea.co.tools/dialoguea/server/adduser.js:17:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

Et `npm run dev` affiche (alors que j'ai bien `DEBUG: true` dans settings.js) :
```
> Dialoguea@0.1.9 dev /var/www/dialoguea.co.tools/dialoguea
> nodemon -w ./server --exec "babel-node server --presets es2015,stage-0"

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /var/www/dialoguea.co.tools/dialoguea/server/**/*
[nodemon] starting `babel-node server --presets es2015,stage-0`
/var/www/dialoguea.co.tools/dialoguea/server/log.js:44
		level: _settings2.default.DEBUG ? 'debug' : 'info',
		                         ^

TypeError: Cannot read property 'DEBUG' of undefined
    at Object.<anonymous> (/var/www/dialoguea.co.tools/dialoguea/server/log.js:32:11)
    at Module._compile (module.js:570:32)
    at loader (/var/www/dialoguea.co.tools/dialoguea/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/var/www/dialoguea.co.tools/dialoguea/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/dialoguea.co.tools/dialoguea/server/index.js:14:1)
[nodemon] app crashed - waiting for file changes before starting...
```

Merci !!

**Comment by flintforge** [comment]
quick workaround b2eb270a598ebcc021347b91213bb244fd86737f
ps : s'il y d'autres problèmes avec l'ajout d'utilisateur en ligne de commande, il vaut mieux ouvrir un autre ticket.
